# Generated by Django 3.2.19 on 2023-08-01 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20230801_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='project_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
