# Generated by Django 3.2.19 on 2023-08-01 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_project_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
