# Generated by Django 3.2.19 on 2023-08-01 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='expire',
            field=models.DateTimeField(null=True),
        ),
    ]
