# Generated by Django 3.2.19 on 2023-08-01 04:43

import ckeditor.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coupons', '0001_initial'),
        ('orders', '0003_auto_20221220_2319'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Acuerdo de confidencialidad y privacidad de información', 'ACUERDO'), ('Contrato de Servicios de Tecnologias de Información (IT)', 'CONTRATO_T'), ('Contrato de Servicios de marketing digital', 'CONTRATO_M'), ('Contrato de Servicios de Consultoria en el departamento de gerencia', 'CONTRATO_CG')], max_length=200, null=True, verbose_name='Contract Type')),
                ('Law_type', models.CharField(choices=[('Juridicamente ', 'JURIDICO'), ('Naturalmente ', 'NATURAL')], max_length=20, null=True, verbose_name='Law Type')),
                ('Cli_title', models.CharField(choices=[('Sr', 'Señor.'), ('Sra', 'Señora.'), ('Sta', 'Señorita.'), ('Ing', 'Ingeniero'), ('Arq', 'Arquitecto'), ('Lic', 'Licenciado'), ('Phd', 'Doctor')], max_length=20, null=True, verbose_name='Title Type')),
                ('Business_type', models.CharField(choices=[('compañia', 'compañia'), ('negocio', 'negocio')], max_length=20, null=True, verbose_name='Business Type')),
                ('Business_name', models.CharField(max_length=100, null=True, verbose_name='Business names')),
                ('first_name', models.CharField(max_length=50, verbose_name='first names')),
                ('last_name', models.CharField(max_length=50, verbose_name='last names')),
                ('CI', models.BigIntegerField(max_length=13, null=True, verbose_name='Identy ID')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('address', models.CharField(max_length=250, verbose_name='address')),
                ('postal_code', models.CharField(max_length=20, verbose_name='postal code')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
                ('country', models.CharField(max_length=100, null=True, verbose_name='country')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('paid', models.BooleanField(default=False)),
                ('braintree_id', models.CharField(blank=True, max_length=150)),
                ('discount', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='coupons.coupon')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='ContractItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='contracts.contract')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_items', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='AcuerdoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clausura', models.CharField(max_length=250, null=True, verbose_name='clausura')),
                ('intro', ckeditor.fields.RichTextField(null=True)),
                ('contract', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Acuerdo_items', to='contracts.contract')),
            ],
        ),
    ]
