# Generated by Django 3.2.19 on 2023-08-12 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sblshop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='SBLProduct',
        ),
    ]
