# Generated by Django 3.2.19 on 2023-08-12 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sblshop', '0002_rename_product_sblproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='sblproduct',
            name='icon',
            field=models.CharField(blank=True, choices=[('legal icon', 'icofont-legal'), ('legal book', 'icofont-law-book'), ('legal ebook', 'icofont-ebook'), ('legal offcie', 'icofont-ui-office')], db_index=True, max_length=200, null=True),
        ),
    ]
