# Generated by Django 3.2.19 on 2023-08-12 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sblshop', '0006_alter_sblproduct_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='sblproduct',
            name='item1',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sblproduct',
            name='item2',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sblproduct',
            name='item3',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sblproduct',
            name='item4',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
    ]
