version: '3.9'

services:
  qnd41_app_stg:
    image: smartquail/qnd41_app_stg:latest
    restart: unless-stopped
    environment:
      - PORT=9000
    env_file:
      - .env
    depends_on:
      - smartquaildb
    expose:
      - 9000
    ports:
      - "9000:9000"
    volumes:
      - static-data-qnd41:/qnd41_app_stg/qnd41_app_stg/qnd41_app_stg/staticfiles
      - static-data-qnd41:/qnd41_app_stg/qnd41_app_stg/qnd41_app_stg/media
      - static-data-qnd41:/qnd41_app_stg/qnd41_app_stg/qnd41_app_stg/static
    networks: 
      - lansmartquail
   # command: sh -c "chmod +x /scripts/migrations.sh && sh /scripts/migrations.sh && sh /scripts/run.sh"

  qnode41_proxy:
    image: smartquail/qnd41_nginx:dev
    restart: always
    env_file:
      - .env_stage
    environment:
      - PORT=80
    depends_on:
      - qnd41_app_stg
    ports:
      - "80:80"
      - "443:443"
    volumes: 
      - static-data-qnd41:/qnd41_app_stg/qnd41_app_stg/qnd41_app_stg/staticfiles
      - static-data-qnd41:/qnd41_app_stg/qnd41_app_stg/qnd41_app_stg/media
      - static-data-qnd41:/qnd41_app_stg/qnd41_app_stg/qnd41_app_stg/static
    networks: 
      - lansmartquail

  smartquaildb:
    image: postgres:13-alpine
    restart: always
    command: -p 5432
    env_file:
      - .env_stage
    ports:
      - "5432:5432"
    expose:
     - 5432
    volumes:
      - smartquaildb_data:/var/lib/postgresql/data/
    networks: 
      - lansmartquail

  redis:
    image: redis:3.0
    restart: always
    expose:
      - 6388
    ports:
      - "6388:6388"
    volumes:
      - redis_data:/data
    entrypoint: redis-server --appendonly yes --port 6380
    networks: 
      - lansmartquail

volumes:
  smartquaildb_data:
  redis_data:
  static-data-qnd41:

networks: 
   lansmartquail:
       driver: bridge