# Generated by Django 4.0.10 on 2024-06-23 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmediasettings',
            name='behance',
        ),
    ]
