# Generated by Django 3.2.19 on 2023-08-26 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solutions_categories',
            name='date',
            field=models.DateField(null=True, verbose_name='Post date'),
        ),
    ]
