# Generated by Django 3.2.19 on 2023-05-15 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0008_add_verbose_name_plural'),
        ('wagtailforms', '0005_alter_formsubmission_form_data'),
        ('wagtailcore', '0083_workflowcontenttype'),
        ('wagtailmenus', '0024_auto_20230512_1757'),
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='index',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='GaleriadeImagenes',
        ),
        migrations.DeleteModel(
            name='Index',
        ),
    ]
