# Generated by Django 4.0.10 on 2024-06-26 23:54

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_remove_socialmediasettings_behance'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='TS_info3',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='project2_info'),
        ),
        migrations.AddField(
            model_name='info',
            name='author_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre de autor'),
        ),
        migrations.AddField(
            model_name='info',
            name='bio3',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Frase relevante segundo parrafo'),
        ),
        migrations.AddField(
            model_name='info',
            name='business_activiy',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Actividad de autor en el negocio'),
        ),
        migrations.AddField(
            model_name='info',
            name='business_experience',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='años de experiencia de autor en el negocio'),
        ),
        migrations.AddField(
            model_name='info',
            name='business_title',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Titulo de autor en el negocio'),
        ),
        migrations.AddField(
            model_name='info',
            name='info5',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='project4_info2'),
        ),
        migrations.AddField(
            model_name='info',
            name='updated',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Fecha de ultima actualización'),
        ),
        migrations.AlterField(
            model_name='info',
            name='TS_info1',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='project_info'),
        ),
        migrations.AlterField(
            model_name='info',
            name='TS_info2',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='project_info2'),
        ),
        migrations.AlterField(
            model_name='info',
            name='TS_info4',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='project3_info'),
        ),
        migrations.AlterField(
            model_name='info',
            name='TS_info5',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='project4_info'),
        ),
        migrations.AlterField(
            model_name='info',
            name='bio2',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Frase relevante primer parrafo'),
        ),
        migrations.AlterField(
            model_name='info',
            name='info3',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='project2_info2'),
        ),
        migrations.AlterField(
            model_name='info',
            name='info4',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='project3_info2'),
        ),
    ]
