# Generated by Django 3.2.19 on 2023-07-13 11:55

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_consultashome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultashome',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='webapp.home'),
        ),
        migrations.AlterField(
            model_name='home',
            name='numero_coffe',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='numero_experiencia',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='numero_horas',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='numero_wins',
            field=models.IntegerField(null=True),
        ),
    ]
