# Generated by Django 3.2.19 on 2023-05-15 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_galeriadeimagenes_home'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='from_address',
        ),
        migrations.RemoveField(
            model_name='home',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='home',
            name='to_address',
        ),
    ]
