# Generated by Django 3.2.19 on 2023-09-19 18:43

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('webapp', '0003_resumepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumepage',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Foto de perfil'),
        ),
        migrations.AlterField(
            model_name='resumepage',
            name='aboutus',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='mensaje 1'),
        ),
        migrations.AlterField(
            model_name='resumepage',
            name='custom_title',
            field=models.CharField(help_text='Nombre', max_length=100),
        ),
    ]
