# Generated by Django 4.0.10 on 2024-06-27 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('webapp', '0004_info_info_title12'),
    ]

    operations = [
        migrations.AddField(
            model_name='galeriadeimagenes',
            name='image_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen Slide Banner 4'),
        ),
    ]
