# Generated by Django 3.2.19 on 2023-09-04 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_articledetailpage_articlelistingpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='articledetailpage',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
