# Generated by Django 3.2.19 on 2023-09-20 20:37

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20230919_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumepage',
            name='aboutus_1',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='mensaje 1'),
        ),
        migrations.AddField(
            model_name='resumepage',
            name='aboutus_2',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='mensaje 2'),
        ),
        migrations.AddField(
            model_name='resumepage',
            name='aboutus_3',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='mensaje 3'),
        ),
        migrations.AlterField(
            model_name='resumepage',
            name='aboutus',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Acerca de mi'),
        ),
    ]
