# Generated by Django 3.2.19 on 2023-09-21 20:13

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('webapp', '0005_auto_20230920_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumepage',
            name='educational_mesange',
            field=models.CharField(help_text='Describir un mensaje de la educación', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resumepage',
            name='experience_mesange',
            field=models.CharField(help_text='Describir un mensaje de experiencia', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resumepage',
            name='porfolio_1',
            field=models.CharField(choices=[('Landscapes', 'Landscapes'), ('Visual Production', 'Visual Production'), ('web content', 'web content'), ('Social Networks content', 'Social Networks content'), ('Web Desing', 'Web Desing'), ('Intelligence Artificial', 'Intelligence Artificial')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resumepage',
            name='porfolio_2',
            field=models.CharField(choices=[('Landscapes', 'Landscapes'), ('Visual Production', 'Visual Production'), ('web content', 'web content'), ('Social Networks content', 'Social Networks content'), ('Web Desing', 'Web Desing'), ('Intelligence Artificial', 'Intelligence Artificial')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resumepage',
            name='porfolio_3',
            field=models.CharField(choices=[('Landscapes', 'Landscapes'), ('Visual Production', 'Visual Production'), ('web content', 'web content'), ('Social Networks content', 'Social Networks content'), ('Web Desing', 'Web Desing'), ('Intelligence Artificial', 'Intelligence Artificial')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resumepage',
            name='porfolio_4',
            field=models.CharField(choices=[('Landscapes', 'Landscapes'), ('Visual Production', 'Visual Production'), ('web content', 'web content'), ('Social Networks content', 'Social Networks content'), ('Web Desing', 'Web Desing'), ('Intelligence Artificial', 'Intelligence Artificial')], max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Porfolio_Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('porfolio_title', models.CharField(help_text='Titulo de porfolio', max_length=100, null=True)),
                ('porfolio', models.CharField(choices=[('Landscapes', 'Landscapes'), ('Visual Production', 'Visual Production'), ('web content', 'web content'), ('Social Networks content', 'Social Networks content'), ('Web Desing', 'Web Desing'), ('Intelligence Artificial', 'Intelligence Artificial')], max_length=100, null=True)),
                ('image_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen 1')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='porfolio_item_Page', to='webapp.resumepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Experience_Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('business_title', models.CharField(help_text='Nombre de la empresa donde trabajo', max_length=100, null=True)),
                ('business_chage', models.CharField(help_text='Nombre del cargo que ocupo', max_length=100, null=True)),
                ('business_activity', models.CharField(help_text='Descripcion de la actividad realizada', max_length=1000, null=True)),
                ('Fecha', models.DateTimeField()),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiece_item_Page', to='webapp.resumepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Educational_Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('academy_title', models.CharField(help_text='Nombre de la institución educativa', max_length=100, null=True)),
                ('title', models.CharField(help_text='Nombre del titulo', max_length=100, null=True)),
                ('academy_activity', models.CharField(help_text='Descripcion de la formación', max_length=1000, null=True)),
                ('Fecha', models.DateTimeField()),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='educational_item_Page', to='webapp.resumepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='contact_form_resume_Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('clean_name', models.CharField(blank=True, default='', help_text='Safe name of the form field, the label converted to ascii_snake_case', max_length=255, verbose_name='name')),
                ('label', models.CharField(help_text='The label of the form field', max_length=255, verbose_name='label')),
                ('field_type', models.CharField(choices=[('singleline', 'Single line text'), ('multiline', 'Multi-line text'), ('email', 'Email'), ('number', 'Number'), ('url', 'URL'), ('checkbox', 'Checkbox'), ('checkboxes', 'Checkboxes'), ('dropdown', 'Drop down'), ('multiselect', 'Multiple select'), ('radio', 'Radio buttons'), ('date', 'Date'), ('datetime', 'Date/time'), ('hidden', 'Hidden field')], max_length=16, verbose_name='field type')),
                ('required', models.BooleanField(default=True, verbose_name='required')),
                ('choices', models.TextField(blank=True, help_text='Comma or new line separated list of choices. Only applicable in checkboxes, radio and dropdown.', verbose_name='choices')),
                ('default_value', models.TextField(blank=True, help_text='Default value. Comma or new line separated values supported for checkboxes.', verbose_name='default value')),
                ('help_text', models.CharField(blank=True, max_length=255, verbose_name='help text')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='webapp.resumepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
