# Generated by Django 4.0.10 on 2024-06-27 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('webapp', '0005_galeriadeimagenes_image_4'),
    ]

    operations = [
        migrations.AddField(
            model_name='galeriadeimagenes',
            name='banner_background',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Backgound en slide'),
        ),
        migrations.AddField(
            model_name='galeriadeimagenes',
            name='logo_slide',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Logotipo en slide'),
        ),
        migrations.AlterField(
            model_name='galeriadeimagenes',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Logotipo en texto '),
        ),
    ]
