# Generated by Django 3.2.19 on 2023-09-04 20:30

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_articledetailpage_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='articledetailpage',
            name='abstract',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Abstract'),
        ),
    ]
