# Generated by Django 3.2.19 on 2023-09-22 14:34

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20230922_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumepage',
            name='thank_you_text',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
