# Generated by Django 3.2.19 on 2023-09-05 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20230905_0341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialmediasettings',
            old_name='behance',
            new_name='pinterest',
        ),
    ]
