# Generated by Django 4.0.10 on 2024-06-27 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('webapp', '0007_alter_info_ts_info6_alter_info_ts_info7_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='galeriadeimagenes',
            name='image_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen Slide Banner 1'),
        ),
        migrations.AddField(
            model_name='galeriadeimagenes',
            name='image_2_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen Slide Banner 1'),
        ),
        migrations.AddField(
            model_name='galeriadeimagenes',
            name='image_3_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen Slide Banner 1'),
        ),
        migrations.AddField(
            model_name='galeriadeimagenes',
            name='image_4_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen Slide Banner 1'),
        ),
    ]
