# Generated by Django 3.2.19 on 2023-09-24 01:54

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_resumepage_thank_you_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumepage',
            name='comments',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Mensaje para que nos dejen un comentario'),
        ),
    ]
