# Generated by Django 3.2.19 on 2023-09-06 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_rename_behance_socialmediasettings_pinterest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='galleria_article_page',
            old_name='image',
            new_name='image_1',
        ),
    ]
