# Generated by Django 4.0.10 on 2024-06-27 15:49

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_galeriadeimagenes_image_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='banner_title13',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Titulo de parrafo-3'),
        ),
        migrations.AddField(
            model_name='info',
            name='banner_title14',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Titulo de parrafo-3'),
        ),
        migrations.AddField(
            model_name='info',
            name='banner_title15',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Titulo de parrafo-3'),
        ),
        migrations.AddField(
            model_name='info',
            name='info_title13',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Descripcion de producto'),
        ),
        migrations.AddField(
            model_name='info',
            name='info_title14',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Descripcion de producto'),
        ),
        migrations.AddField(
            model_name='info',
            name='info_title15',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Descripcion de producto'),
        ),
    ]
