# Generated by Django 3.2.19 on 2023-09-24 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_resumepage_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galeriahome',
            name='image_10',
        ),
        migrations.RemoveField(
            model_name='galeriahome',
            name='image_11',
        ),
        migrations.RemoveField(
            model_name='galeriahome',
            name='image_12',
        ),
        migrations.RemoveField(
            model_name='galeriahome',
            name='image_13',
        ),
        migrations.RemoveField(
            model_name='galeriahome',
            name='image_14',
        ),
        migrations.RemoveField(
            model_name='galeriahome',
            name='image_15',
        ),
        migrations.RemoveField(
            model_name='galeriahome',
            name='image_16',
        ),
        migrations.RemoveField(
            model_name='galeriahome',
            name='image_17',
        ),
        migrations.RemoveField(
            model_name='galeriahome',
            name='image_18',
        ),
        migrations.RemoveField(
            model_name='galeriahome',
            name='image_19',
        ),
        migrations.RemoveField(
            model_name='galeriahome',
            name='image_20',
        ),
        migrations.RemoveField(
            model_name='galeriahome',
            name='image_21',
        ),
        migrations.RemoveField(
            model_name='galeriahome',
            name='image_22',
        ),
        migrations.RemoveField(
            model_name='galeriahome',
            name='image_23',
        ),
        migrations.RemoveField(
            model_name='galeriahome',
            name='image_24',
        ),
        migrations.RemoveField(
            model_name='galeriahome',
            name='image_25',
        ),
        migrations.RemoveField(
            model_name='galeriahome',
            name='image_26',
        ),
        migrations.RemoveField(
            model_name='galeriahome',
            name='image_7',
        ),
        migrations.RemoveField(
            model_name='galeriahome',
            name='image_8',
        ),
        migrations.RemoveField(
            model_name='galeriahome',
            name='image_9',
        ),
    ]
