# Generated by Django 3.2.19 on 2023-09-07 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('webapp', '0010_alter_articledetailpage_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='articledetailpage',
            name='author',
            field=models.CharField(help_text='Author Article', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='articledetailpage',
            name='category',
            field=models.CharField(help_text='Article category', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='articledetailpage',
            name='custom_title',
            field=models.CharField(help_text='Overwrites article title', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='galleria_article_page',
            name='image_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Author picture'),
        ),
    ]
