# Generated by Django 3.2.19 on 2023-09-24 04:54

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_auto_20230924_0434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='bio',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='reseña bibliografica'),
        ),
    ]
