# Generated by Django 3.2.19 on 2023-09-07 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_auto_20230907_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='articledetailpage',
            name='custom_subtitle',
            field=models.CharField(help_text='Overwrites article subtitle', max_length=100, null=True),
        ),
    ]
