# Generated by Django 3.2.19 on 2023-09-07 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_articledetailpage_custom_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='articledetailpage',
            name='bio',
            field=models.CharField(help_text='Author bio', max_length=500, null=True),
        ),
    ]
