# Generated by Django 3.2.19 on 2023-09-08 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('wagtailredirects', '0008_add_verbose_name_plural'),
        ('wagtailforms', '0005_alter_formsubmission_form_data'),
        ('wagtailmenus', '0024_auto_20230512_1757'),
        ('webapp', '0013_articledetailpage_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleria_solutions_blog_page',
            name='image',
        ),
        migrations.RemoveField(
            model_name='galleria_solutions_blog_page',
            name='image_10',
        ),
        migrations.RemoveField(
            model_name='galleria_solutions_blog_page',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='galleria_solutions_blog_page',
            name='image_3',
        ),
        migrations.RemoveField(
            model_name='galleria_solutions_blog_page',
            name='image_4',
        ),
        migrations.RemoveField(
            model_name='galleria_solutions_blog_page',
            name='image_5',
        ),
        migrations.RemoveField(
            model_name='galleria_solutions_blog_page',
            name='image_6',
        ),
        migrations.RemoveField(
            model_name='galleria_solutions_blog_page',
            name='image_7',
        ),
        migrations.RemoveField(
            model_name='galleria_solutions_blog_page',
            name='image_8',
        ),
        migrations.RemoveField(
            model_name='galleria_solutions_blog_page',
            name='image_9',
        ),
        migrations.RemoveField(
            model_name='galleria_solutions_blog_page',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='galleria_solutions_blog_page',
            name='page',
        ),
        migrations.RemoveField(
            model_name='solutions_blog_page',
            name='news_image',
        ),
        migrations.RemoveField(
            model_name='solutions_blog_page',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='solutionsblogpage',
            name='page_ptr',
        ),
        migrations.RenameField(
            model_name='articledetailpage',
            old_name='bio',
            new_name='bio2',
        ),
        migrations.DeleteModel(
            name='comments_solutionsblogPage',
        ),
        migrations.DeleteModel(
            name='galleria_solutions_blog_Page',
        ),
        migrations.DeleteModel(
            name='solutions_blog_Page',
        ),
        migrations.DeleteModel(
            name='SolutionsBlogPage',
        ),
    ]
