# Generated by Django 3.2.19 on 2023-09-08 19:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0008_add_verbose_name_plural'),
        ('wagtailforms', '0005_alter_formsubmission_form_data'),
        ('wagtailmenus', '0024_auto_20230512_1757'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailcore', '0083_workflowcontenttype'),
        ('webapp', '0015_jobslistingopeninggpage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobsListingOpeninggPage',
            new_name='JobsListingOpeningPage',
        ),
    ]
