# Generated by Django 3.2.19 on 2023-09-09 10:49

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_jobsformdetailopeningpage_jobsformopeningpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobslistingopeningpage',
            name='benefits',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Abstract'),
        ),
        migrations.AddField(
            model_name='jobslistingopeningpage',
            name='jobs_category',
            field=models.CharField(choices=[('Marketing & Publishing', 'advertising'), ('UI/UX Developer', 'product'), ('Python/Django Developer', 'tearsheting'), ('Docker Developer', 'landscape'), ('Kubernetes Developer', 'documentary'), ('FullStack Developer', 'documentary'), ('Chief Officer Technologies', 'documentary'), ('Chief Officer', 'documentary')], max_length=100, null=True),
        ),
    ]
