# Generated by Django 3.2.19 on 2023-09-09 12:18

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0018_auto_20230909_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsformdetailopeningpage',
            name='city',
            field=models.CharField(choices=[('Quito', 'Quito'), ('Guayaquil', 'Guayaquil'), ('Cuenca', 'Cuenca'), ('Buenos Aires', 'Buenos Aires'), ('Mendoza', 'Mendoza'), ('Paris', 'Paris'), ('Lausanne', 'Lausanne'), ('New York', 'New York')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobsformdetailopeningpage',
            name='country',
            field=models.CharField(choices=[('Ecuador', 'Ecuador'), ('Switzerland', 'Switzerland'), ('Argentina', 'Argentina'), ('France', 'France'), ('United States', 'United States')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobsformdetailopeningpage',
            name='description',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Beneficios'),
        ),
        migrations.AddField(
            model_name='jobsformdetailopeningpage',
            name='jobs_category',
            field=models.CharField(choices=[('Community Manager senior', 'Community Manager senior'), ('Community Manager Junior', 'Community Manager Juniorr'), ('Content Designer senior', 'Content Designer senior'), ('Content Designer junior', 'Docker Developer junior'), ('Project Manager senior', 'Project Manager senior'), ('Project Manager junior', 'Project Manager junior'), ('UI/UX Desinger senior', 'UI/UX Desinger senior'), ('UI/UX Desinger junior', 'UI/UX Desinger junior'), ('Django Developer senior', 'Django Developer senior'), ('Django Developer junior', 'Django Developer junior'), ('System Reliability Engineer junior', 'System Reliability Engineer junior'), ('System Reliability Engineer senior', 'System Reliability Engineer senior')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobsformdetailopeningpage',
            name='timejobs',
            field=models.CharField(choices=[('Part Time', 'Part Time'), ('Full Time', 'Ful Time')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobslistingopeningpage',
            name='benefits',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Beneficios'),
        ),
        migrations.AlterField(
            model_name='jobslistingopeningpage',
            name='jobs_category',
            field=models.CharField(choices=[('Marketing & Publishing', 'Marketing & Publishing'), ('UI/UX Developer', 'UI/UX Developer'), ('Python/Django Developer', 'Python/Django Developer'), ('Docker Developer', 'Docker Developer'), ('Kubernetes Developer', 'Kubernetes Developer'), ('FullStack Developer', 'FullStack Developer'), ('Chief Officer Technologies', 'Chief Officer Technologies'), ('Chief Officer', 'Chief Officer')], max_length=100, null=True),
        ),
    ]
