# Generated by Django 3.2.19 on 2023-09-09 12:40

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0019_auto_20230909_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobsformdetailopeningpage',
            name='abstract',
        ),
        migrations.RemoveField(
            model_name='jobsformdetailopeningpage',
            name='author',
        ),
        migrations.RemoveField(
            model_name='jobsformdetailopeningpage',
            name='bio2',
        ),
        migrations.RemoveField(
            model_name='jobsformdetailopeningpage',
            name='blog_image',
        ),
        migrations.RemoveField(
            model_name='jobsformdetailopeningpage',
            name='category',
        ),
        migrations.RemoveField(
            model_name='jobsformdetailopeningpage',
            name='custom_subtitle',
        ),
        migrations.RemoveField(
            model_name='jobsformdetailopeningpage',
            name='custom_title',
        ),
        migrations.RemoveField(
            model_name='jobsformdetailopeningpage',
            name='date',
        ),
        migrations.AlterField(
            model_name='jobsformdetailopeningpage',
            name='description',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Descripción corta'),
        ),
    ]
