# Generated by Django 3.2.19 on 2023-09-09 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0020_auto_20230909_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsformdetailopeningpage',
            name='uploadcv',
            field=models.FileField(blank=True, null=True, upload_to='CV_file/%Y/%m/%d'),
        ),
    ]
