# Generated by Django 3.2.19 on 2023-09-11 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0021_jobsformdetailopeningpage_uploadcv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsformopeningpage',
            name='field_type',
            field=models.CharField(max_length=16, verbose_name='field type'),
        ),
    ]
