# Generated by Django 3.2.19 on 2023-09-11 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('webapp', '0024_jobsformopeningpage_uploaded_image_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobsformopeningpage',
            name='uploaded_image_collection',
        ),
        migrations.AddField(
            model_name='jobsformdetailopeningpage',
            name='uploaded_image_collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailcore.collection'),
        ),
    ]
