# Generated by Django 3.2.19 on 2023-09-11 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0026_jobsformopeningpage_uploaded_image_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobsformopeningpage',
            name='uploaded_image_collection',
        ),
    ]
