# Generated by Django 3.2.19 on 2023-09-12 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('webapp', '0028_galleria_resources_page_resourceslistingpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourceslistingpage',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Banner'),
        ),
        migrations.DeleteModel(
            name='galleria_resources_Page',
        ),
    ]
