# Generated by Django 3.2.19 on 2023-08-12 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='logo',
        ),
    ]
