name: SmartQuail Django-app & Postgress Test

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]
 
jobs:
  test_qnode01_app:
    uses: smartquailDev/qnode0_app/.github/workflows/test-qnode0_app.yaml@main
  Docker_qnode01:
    runs-on: ubuntu-latest
    needs: [test_qnode0_app]
    env:
      DJANGO_SECRET_KEY: test-key-not-good
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DO_API_TOKEN_KEY }}
    - name: Login to Do Container Registry with short-lived creds
      run: doctl registry login --expiry-seconds 1200
    - name: Build container image
      working-directory: ./qnode0_k8s
      run: | 
        docker build -f Dockerfile \
            -t registry.digitalocean.com/smartquail/qnode0_app:latest \
            -t registry.digitalocean.com/smartquail/qnode0_app:${GITHUB_SHA::7}-${GITHUB_RUN_ID::5} \
            .
    - name: Push Image
      run: | 
        docker push registry.digitalocean.com/smartquail/qnode0_app --all-tags
    - name: k8s cluster kubeconfig file with /short-lived creds
      run: |
        doctl kubernetes cluster kubeconfig save --expiry-seconds 600 ${{env.CLUSTER_NAME}}
   
    - name: Update Deployment secrets
      run: |
          cat << EOF >> web/.env.prod
          AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DJANGO_SUPERUSER_USERNAME=${{ secrets.DJANGO_SUPERUSER_USERNAME }}
          DJANGO_SUPERUSER_PASSWORD=${{ secrets.DJANGO_SUPERUSER_PASSWORD }}
          DJANGO_SUERPUSER_EMAIL=${{ secrets.DJANGO_SUERPUSER_EMAIL }}
          DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}
          ENV_ALLOWED_HOST=${{ secrets.ENV_ALLOWED_HOST }}
          POSTGRES_DB=${{ secrets.POSTGRES_DB }}
          POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_USER=${{ secrets.POSTGRES_USER }}
          POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}
          POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}
          EOF
          kubectl delete secret qnode0_app-prod-env
          kubectl create secret generic qnode0_app-prod-env--from-env-file=qnode0_app/.env.prod

    - name: Update Deployment image
      run: |
        kubectl set image deployment/qnode0_app-deployment qnode0-k8s=registry.digitalocean.com/smartquails/qnode0_app:${GITHUB_SHA::7}-${GITHUB_RUN_ID:: 5}
    - name: Wait for rollout to finish
      run: | 
        kubectl rollout status deployment/qnode0_app-deployment
    - name: Migrate Database command
      run: | 
        export SINGLE_POD_NAME=$(kubectl get pod -l app=qnode0_app-deployment -o jsonpath="{.items[0].metadata.name}")
        kubectl exec -it $SINGLE_POD_NAME -- sh /scripts/migrations.sh
        kubectl exec -it $SINGLE_POD_NAME -- sh /scripts/collectstatic.sh

       

   
